import fs from "node:fs";
import path from "node:path";
import type { Question, QuestionDifficulty } from "../src/types/question";

type AuthoredExamName = "SIE" | "Series 7" | "Series 65" | "Series 66";
interface ConceptSeed {
  tag: string;
  stem: string;
  options: string[];
  correct: number;
  explanation: string;
}

type FrameBuilder = (_context: string, stem: string) => string;

const outDir = path.join(__dirname, "..", "src", "data", "authoredQuestions");
const D: Record<AuthoredExamName, QuestionDifficulty> = {
  SIE: "trainee",
  "Series 7": "advisor",
  "Series 65": "associate",
  "Series 66": "senior"
};
const C: Record<AuthoredExamName, number> = { SIE: 62, "Series 7": 30, "Series 65": 45, "Series 66": 28 };
const L = {
  sie: ["Knowledge of Capital Markets", "Understanding Products and Their Risks", "Understanding Trading, Customer Accounts and Prohibited Activities", "Overview of the Regulatory Framework"],
  s7: ["Seeks Business for the Broker-Dealer from Customers and Potential Customers", "Opens Accounts After Obtaining and Evaluating Customers' Financial Profile and Investment Objectives", "Provides Customers with Information about Investments, Makes Recommendations, Transfers Assets and Maintains Appropriate Records", "Obtains and Verifies Customers' Purchase and Sales Instructions and Agreements; Processes, Completes, and Confirms Transactions"],
  s65: ["Economic Factors and Business Information", "Investment Vehicle Characteristics", "Client Investment Recommendations and Strategies", "Laws, Regulations, and Guidelines Including Prohibition on Unethical Business Practices"],
  s66: ["Economic Factors and Business Information", "Investment Vehicle Characteristics", "Client/Customer Investment Recommendations and Strategies", "Laws, Regulations, and Guidelines Including Prohibition on Unethical Business Practices"]
};

function q(exam: AuthoredExamName, domain: string, tag: string, question: string, options: string[], correct: number, explanation: string): Question {
  return { exam, domain, difficulty: D[exam], cooldown: C[exam], topicTag: tag, question, options, correct, explanation, points: 10 };
}
function c(tag: string, stem: string, options: string[], correct: number, explanation: string): ConceptSeed { return { tag, stem, options, correct, explanation }; }
function writeExamFile(key: string, constName: string, questions: Question[]): void {
  const file = path.join(outDir, `${key}.ts`);
  const source = `import type { Question } from "../../types/question";\n\nexport const ${constName} = ${JSON.stringify(questions, null, 2)} satisfies Question[];\n`;
  fs.writeFileSync(file, source);
}
const frames: FrameBuilder[] = [
  (_ctx, stem) => stem,
  (_ctx, stem) => `A client scenario asks: ${stem}`,
  (_ctx, stem) => `Which response is most accurate? ${stem}`,
  (_ctx, stem) => `Which answer best fits this situation? ${stem}`
];
const contexts = ["standard practice", "client review", "study drill", "compliance review"];
function expand(exam: AuthoredExamName, domain: string, prefix: string, concepts: ConceptSeed[], target: number): Question[] {
  const out: Question[] = [];
  concepts.forEach((x, i) => frames.forEach((f, j) => out.push(q(exam, domain, `${prefix}-${x.tag}-${j + 1}`, f(contexts[(i + j) % contexts.length], x.stem), x.options, x.correct, x.explanation))));
  let n = 0;
  while (out.length < target) {
    const x = concepts[n % concepts.length];
    out.push(q(exam, domain, `${prefix}-${x.tag}-x${n + 1}`, frames[(n + 1) % frames.length](contexts[(n + 2) % contexts.length], x.stem), x.options, x.correct, x.explanation));
    n += 1;
  }
  return out.slice(0, target);
}

const sieCapital = [
  c("primary-market", "When an issuer sells newly issued securities and receives the proceeds, in which market is the sale taking place?", ["Primary market", "Secondary market", "Money market", "Third market"], 0, "The primary market is where issuers raise capital by selling new securities. Secondary markets are where investors trade outstanding securities with one another."),
  c("fed-policy", "The Federal Reserve lowers short-term rates and buys Treasury securities. What outcome is it most directly seeking?", ["Stimulate economic activity", "Reduce bank reserves immediately", "Eliminate equity market risk", "Register new issues"], 0, "Lower rates and open-market purchases are expansionary tools. They are intended to add liquidity and support borrowing and spending."),
  c("yield-curve", "A normal Treasury yield curve generally means what?", ["Long-term yields are higher than short-term yields", "Short-term yields always exceed long-term yields", "All maturities have the same yield", "Treasuries do not respond to maturity"], 0, "A normal yield curve usually slopes upward. Investors generally demand more yield for longer maturities."),
  c("inflation", "Which risk is most directly present when rising prices reduce the purchasing power of bond interest payments?", ["Inflation risk", "Call risk", "Proxy risk", "Transfer risk"], 0, "Inflation risk is the danger that future dollars will buy less. Fixed-income investors are especially exposed to that erosion."),
  c("secondary-market", "An investor sells exchange-listed stock to another investor. Which market is involved?", ["Secondary market", "Primary market", "Private placement market", "Treasury auction market"], 0, "Once securities have been issued, investor-to-investor trading occurs in the secondary market. The issuer does not receive the proceeds."),
  c("capital-formation", "What is the main economic purpose of securities markets?", ["Channel capital from savers to users of capital", "Guarantee investment profits", "Replace banks completely", "Eliminate recessions"], 0, "Securities markets help move funds from investors to issuers that need capital. That process supports business activity and economic growth."),
  c("credit-spread", "Why do lower-rated corporate bonds usually offer higher yields than Treasuries?", ["Investors require compensation for higher credit risk", "They have lower duration", "They are tax-exempt", "They eliminate default risk"], 0, "Lower-rated issuers have more credit risk than the U.S. Treasury. Investors demand a higher yield spread as compensation."),
  c("currency-risk", "A U.S. investor buys foreign equities and worries that exchange-rate moves could reduce returns. What risk is this?", ["Currency risk", "Prepayment risk", "Call risk", "Breakpoint risk"], 0, "Foreign investments add currency exposure when returns are translated back into dollars. Exchange-rate moves can help or hurt total return.")
];
const sieProducts = [
  c("common-stock", "Which feature is most associated with common stock?", ["Voting rights and residual ownership", "A fixed maturity date", "Guaranteed dividends", "Priority over secured creditors"], 0, "Common stock represents ownership in a corporation and usually carries voting rights. Common shareholders stand behind creditors in liquidation."),
  c("mutual-fund", "An open-end investment company generally issues and redeems shares at what price basis?", ["Next computed NAV", "A negotiated exchange price", "Par value", "Stated redemption value"], 0, "Open-end mutual funds transact at the next computed net asset value after the order is accepted. They do not trade intraday like stocks."),
  c("etf", "Which statement best describes an ETF?", ["It trades intraday on an exchange", "It can be purchased only from the issuer at par", "It always uses active management", "It cannot hold bonds"], 0, "ETFs trade during the day like stocks on an exchange. Many are passive, but the key structural point is intraday market trading."),
  c("corp-bond", "What is a core feature of a corporate bond?", ["It is a debt obligation of the issuer", "It represents residual ownership", "It has no credit risk", "It always matures in one year or less"], 0, "A corporate bond makes the investor a creditor of the corporation. Bondholders receive stated interest and repayment of principal at maturity if the issuer remains solvent."),
  c("option-call", "What right does a listed call option give its holder?", ["The right to buy the underlying security at the strike price", "The right to sell the underlying security at the strike price", "A guaranteed dividend", "A right to redeem fund shares at cost"], 0, "A call gives the holder the right, but not the obligation, to buy the underlying security at the strike price. The premium paid is the buyer's maximum loss."),
  c("option-put", "What right does a listed put option give its holder?", ["The right to sell the underlying security at the strike price", "The right to buy the underlying security at the strike price", "Federal insurance on principal", "A right to vote as a shareholder"], 0, "A put gives the holder the right to sell the underlying security at the strike price. Investors use puts for downside protection or bearish speculation."),
  c("reit", "A REIT primarily offers exposure to what asset class?", ["Real estate and related income-producing properties", "Foreign currencies only", "Treasury bills only", "Insurance reserves"], 0, "REITs pool money to invest in real estate or real-estate-related assets. They often appeal to investors seeking income and real estate exposure."),
  c("variable-annuity", "What is a key risk of a variable annuity before annuitization?", ["The account value can fluctuate with market performance", "The insurer guarantees stocklike gains", "The contract is FDIC insured", "The owner avoids all surrender charges"], 0, "Variable annuity subaccounts rise and fall with investment performance. The contract can therefore lose value, even though it is an insurance product."),
  c("dpp", "What is a common feature of a direct participation program?", ["Pass-through tax or cash-flow attributes and limited liquidity", "Daily redemption at NAV", "Federal insurance of principal", "Guaranteed current income"], 0, "Direct participation programs often pass economic results through to investors. They are usually relatively illiquid and more complex than traditional securities."),
  c("muni", "A municipal bond backed by a specific project's revenues is what type of bond?", ["Revenue bond", "General obligation bond", "Treasury bond", "Equipment trust certificate"], 0, "Revenue bonds are supported by a defined revenue source rather than the issuer's full taxing power. Project viability is a key credit consideration.")
];
const sieTrading = [
  c("cash-account", "If a customer buys securities in a cash account, when is full payment generally due?", ["By settlement date", "Within 30 calendar days", "At tax filing time", "Only after resale"], 0, "Cash-account purchases must generally be paid for by settlement date. Failure to do so can lead to account restrictions."),
  c("stop-order", "Which order becomes a market order once the stop price is reached?", ["Stop order", "Limit order", "Fill-or-kill order", "Market-on-close order"], 0, "A stop order is triggered at the stop price and then becomes a market order. It may execute at a price different from the trigger."),
  c("limit-order", "Which order sets the maximum price a buyer will pay or the minimum price a seller will accept?", ["Limit order", "Stop order", "Market order", "All-or-none order"], 0, "A limit order provides price control by specifying the worst acceptable price. The trade may not execute if the market never reaches that price."),
  c("discretion", "When may a representative exercise ongoing discretion in a customer's account?", ["After written discretionary authority is accepted by the firm", "Whenever the representative believes a trade is suitable", "Only in a cash account", "Never"], 0, "Discretion generally must be granted in writing and accepted by the firm. Without it, the representative cannot choose trades or timing on the customer's behalf."),
  c("insider", "Trading while in possession of material nonpublic information most directly violates what?", ["Antifraud and insider trading prohibitions", "Only margin maintenance rules", "Only prospectus delivery rules", "Only blue-sky filing rules"], 0, "Material nonpublic information cannot be used for trading or tipping others. Doing so undermines market integrity and violates securities laws."),
  c("front-running", "A representative buys a stock for a personal account before entering a large customer buy order in the same stock. What is this?", ["Front running", "Breakpoint sale", "Hedging", "Rights offering"], 0, "Front running occurs when a person trades ahead of a customer order while knowing the order could affect price. It is a prohibited practice."),
  c("churning", "Excessive trading in a customer's account mainly to generate commissions is known as what?", ["Churning", "Laddering", "Arbitrage", "Hedging"], 0, "Churning is excessive trading inconsistent with the customer's profile and driven by compensation motives. It is unethical and potentially fraudulent."),
  c("best-execution", "The duty of best execution requires a broker-dealer to seek what?", ["The most favorable reasonably available terms for customer orders", "The fastest execution regardless of price", "The highest commission", "Only exchange-listed liquidity"], 0, "Best execution requires firms to consider price and other execution factors. The goal is the most favorable reasonably available terms under the circumstances."),
  c("aml", "Customer identification procedures are most directly associated with what goal?", ["Anti-money-laundering compliance", "Market making", "Stock dividends", "Rule 144 resales"], 0, "Customer identification programs are part of AML compliance. Firms verify identity to reduce money laundering and related risks."),
  c("joint", "In a joint account with rights of survivorship, what typically happens when one owner dies?", ["Ownership passes to the surviving owner or owners", "The account always enters probate first", "The account must be liquidated", "The broker-dealer becomes temporary owner"], 0, "JTWROS accounts generally pass automatically to surviving owners. That feature distinguishes them from tenancy in common.")
];
const sieReg = [
  c("1933", "The Securities Act of 1933 primarily governs what?", ["The initial distribution of new securities", "Only secondary-market trading", "State adviser registration", "Bank reserve requirements"], 0, "The 1933 Act focuses on the offer and sale of new securities. Its framework centers on registration and disclosure in the primary market."),
  c("1934", "The Securities Exchange Act of 1934 is most directly associated with what?", ["Secondary market regulation and ongoing reporting", "Insurance reserve accounting", "ERISA planning", "Probate administration"], 0, "The 1934 Act created the SEC and regulates many aspects of trading markets, broker-dealers, and periodic issuer reporting. It is a core secondary-market statute."),
  c("finra", "FINRA is best described as what type of organization?", ["A self-regulatory organization for broker-dealers", "A federal court", "A state legislature", "A transfer agent"], 0, "FINRA is an SRO that oversees broker-dealers and associated persons. Its rules are subject to SEC oversight."),
  c("sipc", "SIPC protection is designed to address which risk?", ["Missing customer assets at a failed broker-dealer, within limits", "Losses from a falling stock market", "Unsuitable recommendations", "Interest-rate risk"], 0, "SIPC protects customers when a brokerage fails and customer assets are missing, up to statutory limits. It does not insure against market losses."),
  c("msrb", "The MSRB writes rules primarily for what market?", ["Municipal securities", "Commodity futures", "Treasury auctions", "Private mortgages"], 0, "The Municipal Securities Rulemaking Board creates rules for municipal securities dealers and municipal advisors. Enforcement occurs through regulators such as FINRA and the SEC."),
  c("reg-bi", "Regulation Best Interest applies most directly when a broker-dealer does what?", ["Makes a recommendation to a retail customer", "Executes an unsolicited institutional trade", "Audits an issuer", "Administers an estate"], 0, "Reg BI governs broker-dealer recommendations to retail customers. It requires the recommendation to be made in the retail customer's best interest."),
  c("anti-fraud", "What principle underlies much of federal securities regulation?", ["Antifraud and full and fair disclosure", "Guaranteed returns", "Federal insurance for all securities", "Mandatory active management"], 0, "Securities laws are largely disclosure-based and antifraud-focused. They do not guarantee investment success or remove investment risk.")
];
const s7F1 = [
  c("prospecting", "Which activity is part of seeking business for a broker-dealer?", ["Prospecting for potential customers using approved communications", "Settling customer trades", "Calculating issuer taxes", "Opening trust accounts"], 0, "Function 1 covers prospecting and communications with customers and prospects. That work must still comply with communication standards."),
  c("retail-comm", "A broadly distributed advertisement to retail investors is generally treated as what?", ["Retail communication", "Only correspondence", "An order ticket", "A prospectus supplement"], 0, "Communications categories matter because supervision and approval requirements vary. Broad retail distribution generally falls under retail communication rules."),
  c("testimonial", "If a social media post includes a customer testimonial, what should the firm consider first?", ["Communication and disclosure rules", "Whether it guarantees performance", "Whether the customer can approve trades", "Whether it replaces account forms"], 0, "Testimonials can trigger special advertising and disclosure considerations. Firms must supervise them for balance and fairness."),
  c("gifts", "What is generally true about gifts to clients?", ["They are subject to limits and supervision", "They may always be unlimited if disclosed orally", "They replace suitability duties", "They are allowed only for institutions"], 0, "Gifts and gratuities are restricted because they can create conflicts or improper influence. Firms typically have written standards and monitoring."),
  c("seminar", "A seminar for prospective clients must avoid what?", ["Misleading statements or promissory claims", "Balanced discussion of risk", "Approved educational materials", "Reasonable attendance limits"], 0, "Seminars are a form of communication with the public. They must be fair and balanced and cannot promise results."),
  c("recordkeeping", "Why does a broker-dealer retain business-development communications?", ["To meet supervisory and recordkeeping obligations", "To avoid suitability review", "To replace customer agreements", "To waive disclosure rules"], 0, "Communications must often be retained so the firm can demonstrate compliance and supervision. Recordkeeping supports regulatory review.")
];
const s7F2 = [
  c("cip", "Which information is central to a customer identification program at account opening?", ["Enough information to verify the customer's identity", "The issuer's dividend history", "The branch's commission rate", "The latest CPI reading"], 0, "Customer identification is part of AML and account-opening controls. Firms need sufficient information to verify identity."),
  c("trusted-contact", "Why might a firm request a trusted contact person for a retail account?", ["To have a contact in cases of suspected exploitation or diminished capacity", "To approve every trade automatically", "To replace beneficiary designations", "To guarantee margin loans"], 0, "A trusted contact can help in limited circumstances involving customer protection. It does not itself create trading authority."),
  c("profile", "Before making recommendations, a representative should gather which kind of information?", ["Risk tolerance, time horizon, liquidity needs, and objectives", "Only favorite sectors", "Only branch inventory levels", "Only the last trade ticket"], 0, "Recommendations depend on a full customer profile. Risk tolerance alone is not enough."),
  c("options-approval", "What generally must occur before a customer can trade options?", ["The account must be approved for options trading", "The customer must already own the stock", "The customer must be an institution", "The trade must be unsolicited"], 0, "Options trading requires specific approval because of the strategy and risk considerations involved. Firms review suitability before granting approval."),
  c("margin-agreement", "When opening a margin account, which document gives the firm the right to pledge securities as collateral?", ["Hypothecation agreement", "Proxy statement", "Official statement", "Trust agreement"], 0, "The hypothecation agreement permits the firm to pledge customer securities in connection with the margin loan. Margin accounts involve specific credit-related disclosures."),
  c("entity-account", "When opening an account for a corporation or partnership, the firm should verify what first?", ["Who is authorized to act for the entity", "Only the mailing address", "The stock's closing price", "The branch's advertising budget"], 0, "Entity accounts require authority documentation. The firm must know who is permitted to act for the organization.")
];
const s7F4 = [
  c("order-entry", "Why must customer order instructions be entered accurately and promptly?", ["To support correct execution and customer protection", "To waive best execution", "To eliminate risk", "To replace account-opening forms"], 0, "Order handling is an execution and operations function. Accuracy helps prevent customer harm and regulatory issues."),
  c("settlement", "After execution, what step completes the exchange of money and securities?", ["Settlement", "Prospecting", "Blue-sky filing", "Underwriting"], 0, "Settlement is when payment and delivery are completed. It is separate from the recommendation and account-opening stages."),
  c("confirm", "What document must customers generally receive after a securities transaction?", ["A trade confirmation", "A corporate charter", "A proxy statement for another issuer", "A revised tax return"], 0, "Trade confirmations summarize executed transaction details. They help customers verify what the firm did."),
  c("good-delivery", "In operations, 'good delivery' most directly refers to what?", ["Proper transfer of securities in deliverable form", "A balanced sales presentation", "An approved cold-call script", "A municipal tax opinion"], 0, "Good delivery means the securities and related documentation are in proper form for transfer. This is a post-trade operational concept."),
  c("stop-vs-stop-limit", "What is the key difference between a stop order and a stop-limit order after the trigger is reached?", ["A stop becomes a market order while a stop-limit becomes a limit order", "A stop-limit guarantees execution", "A stop can only be used in bonds", "A stop-limit avoids all price risk"], 0, "A stop order favors execution once triggered, while a stop-limit preserves a price boundary but may not fill. The distinction matters in volatile markets."),
  c("transfers", "When a customer moves assets to another broker-dealer, what must be handled carefully?", ["Transfer instructions and asset movement processing", "The issuer's dividend policy only", "The branch's seminar budget", "Only the account nickname"], 0, "Account transfers require accurate instructions and coordination between firms. Errors can delay access to assets or create customer harm.")
];
const s65Econ = [
  c("gdp", "Gross domestic product is best described as what?", ["The market value of final goods and services produced within a country", "Total imports only", "All corporate bond issuance", "The federal deficit"], 0, "GDP is a broad measure of economic output. It helps advisers assess economic growth trends."),
  c("cpi", "The Consumer Price Index is most commonly used to measure what?", ["Inflation at the consumer level", "Credit spreads", "Bond duration", "Settlement speed"], 0, "The CPI tracks changes in consumer prices over time. It is a standard inflation measure."),
  c("yield-curve", "An inverted yield curve is often interpreted as a possible sign of what?", ["Economic slowdown or recession risk", "Guaranteed stock gains", "Automatic lower taxes", "Rising mutual fund breakpoints"], 0, "An inverted curve has historically been watched as a potential recession indicator. It reflects unusual short-versus-long rate relationships."),
  c("real-return", "A real return is nominal return adjusted for what?", ["Inflation", "Par value", "Commissions only", "The market close"], 0, "Real return measures purchasing power after inflation. It is often more meaningful than nominal return in long-term planning."),
  c("systematic", "Systematic risk is best managed primarily through what?", ["Asset allocation across asset classes", "Owning two stocks in the same industry", "Ignoring macro data", "Only short-term trading"], 0, "Systematic risk affects broad markets and cannot be diversified away within one asset class alone. Asset allocation is a core tool for managing it."),
  c("currency", "Unhedged foreign investing adds what additional risk for a U.S. client?", ["Currency risk", "Breakpoint risk", "Proxy risk", "Custody risk"], 0, "Exchange-rate movement can materially affect returns once foreign gains or losses are translated back into dollars. That is separate from local market performance.")
];
const s65Vehicles = [
  c("equity", "Common stock investors generally expect return from what sources?", ["Capital appreciation and dividends", "Coupon interest and maturity value", "Tax credits and depletion only", "Guaranteed annuity payments"], 0, "Equity returns generally come from price appreciation and dividends. Stocks do not promise principal repayment at maturity."),
  c("zero", "What is a defining feature of a zero-coupon bond?", ["It pays no periodic interest and is issued at a discount", "It has no interest-rate risk", "It is always tax-free", "It can only be issued by municipalities"], 0, "Zero-coupon bonds do not make regular coupon payments. Their return comes from accretion toward par."),
  c("share-class", "Why do mutual fund share classes matter in a recommendation?", ["Different classes can carry different fee structures", "They change whether the portfolio holds stocks or bonds", "They remove the need for a prospectus", "They guarantee different returns"], 0, "Share-class costs can materially affect long-term returns. Advisers should consider fees and the client's intended holding period."),
  c("annuity-in-ira", "Why should an annuity inside an IRA be reviewed carefully?", ["Its tax deferral may duplicate the IRA's tax deferral", "IRAs cannot hold annuities", "Annuities always lose money", "It avoids all surrender charges"], 0, "If an account is already tax-deferred, an additional tax-deferral wrapper may add limited value. Advisers should weigh costs and features carefully."),
  c("private-placement", "What is a common concern with private placements?", ["Limited liquidity and reduced public disclosure", "Guaranteed principal at maturity", "Daily exchange pricing", "Automatic suitability"], 0, "Private placements are often less liquid and less transparent than registered public offerings. They may be suitable only for clients who can evaluate and bear those risks."),
  c("money-market", "What role does a money market fund generally serve in planning?", ["Liquidity management and capital preservation", "Long-term aggressive growth", "Leveraged speculation", "Estate equalization"], 0, "Money market funds are commonly used for cash management. They are not meant to be primary long-term growth engines.")
];
const s65Recs = [
  c("allocation", "For a client with a long time horizon and solid risk capacity, what approach is generally more suitable than a one-stock portfolio?", ["A diversified allocation aligned with goals", "Maximum concentration in one issuer", "All cash indefinitely", "Only illiquid alternatives"], 0, "Diversification and objective alignment usually produce a more defensible recommendation than extreme concentration. The entire client profile should guide portfolio structure."),
  c("asset-location", "Placing tax-inefficient investments in tax-advantaged accounts is an example of what?", ["Asset location", "Market timing", "Price averaging", "Capital budgeting"], 0, "Asset location focuses on where investments are held from a tax perspective. It can improve after-tax outcomes without changing the overall allocation."),
  c("sequence", "A newly retired client drawing from a portfolio should be especially concerned with what risk?", ["Sequence-of-returns risk", "Proxy voting risk", "Transfer risk", "Breakpoint risk"], 0, "Poor returns early in retirement combined with withdrawals can damage long-term sustainability. That is the essence of sequence risk."),
  c("liquidity", "Why might illiquid private real estate be unsuitable for a client with unstable employment income?", ["The client may need access to cash before the investment can be sold", "The investment is federally insured", "The investment has no market risk", "The client can always redeem daily"], 0, "Liquidity needs are a core suitability factor. Illiquid assets can create serious problems for clients who may need quick access to funds."),
  c("tax-loss", "Selling a losing investment to offset gains is what strategy?", ["Tax-loss harvesting", "Duration matching", "Dollar-cost averaging", "Breakpoint accumulation"], 0, "Tax-loss harvesting can improve after-tax returns by using losses against gains, subject to applicable rules. It is a tax-aware portfolio management tool."),
  c("beneficiary", "Why should beneficiary designations be reviewed periodically?", ["They often control transfer regardless of a will", "They matter only for margin accounts", "They automatically change every year", "They replace trusts"], 0, "Beneficiary designations can override other estate documents for many account types. Outdated designations can undermine the client's current plan.")
];
const s65Laws = [
  c("usa", "The Uniform Securities Act is primarily a model law for what?", ["State regulation of securities activities", "Federal tax collection", "Bank reserve policy", "ERISA funding"], 0, "The Uniform Securities Act provides a model framework for state securities regulation. States use versions of it for registration, antifraud, and enforcement."),
  c("iaa", "Under the Investment Advisers Act of 1940, an investment adviser generally gives advice about securities for what?", ["Compensation of any kind", "Only hourly fees", "Only commissions", "Only interest income"], 0, "The federal definition of investment adviser is broad. Compensation can take many forms and does not have to be labeled a fee."),
  c("fiduciary", "What does fiduciary duty require of an investment adviser?", ["Loyalty and care in acting for the client's benefit", "Maximizing product sales", "Guaranteeing returns", "Avoiding written disclosure"], 0, "Fiduciary duty requires advisers to put client interests first and manage conflicts honestly. It does not require guaranteed performance."),
  c("custody", "If an adviser has custody of client assets, what becomes especially important?", ["Safeguards and custody-related compliance controls", "Eliminating ADV delivery", "Ignoring surprise exams", "Waiving client consent"], 0, "Custody raises major investor-protection concerns because client assets can be misused. The rules often require additional safeguards and disclosures."),
  c("adv", "What is Form ADV Part 2 mainly used for?", ["Narrative disclosure to clients about the advisory business", "Registering a public offering", "Opening a margin account", "Confirming a trade"], 0, "Form ADV Part 2 is the adviser's brochure. It explains services, fees, conflicts, and disciplinary information in narrative form."),
  c("marketing", "Which statement is most accurate about adviser advertising?", ["It must not be misleading and must satisfy applicable marketing rules", "It may guarantee future returns if fees are disclosed", "It is exempt from antifraud standards", "It can omit risks if performance is strong"], 0, "Adviser advertising is subject to antifraud principles and specific marketing rules. Balanced, accurate disclosure is required.")
];
const s66Econ = [
  c("cycle", "A contraction phase in the business cycle is generally associated with what?", ["Weakening output and employment", "Guaranteed stock gains", "Automatic lower taxes", "Zero credit risk"], 0, "Series 66 still tests economic concepts because recommendations depend on market conditions. Contractions are associated with slower activity and softer labor markets."),
  c("inflation", "Rising inflation most directly threatens what for a client living on fixed cash flow?", ["Purchasing power", "Transfer-agent capacity", "Registration status", "Position limits"], 0, "Inflation erodes what a stream of dollars can buy. That makes purchasing power a key planning issue."),
  c("rates", "When market interest rates rise sharply, which bonds are generally most price sensitive?", ["Long-duration bonds", "Very short-term Treasury bills", "Money market positions", "Cash sweep balances"], 0, "Longer-duration bonds have greater sensitivity to changes in yield. That is a core fixed-income risk concept."),
  c("systematic", "Systematic market risk is best addressed by what broad tool?", ["Asset allocation", "Owning one additional stock", "Ignoring macro data", "Avoiding statements"], 0, "Systematic risk affects broad markets and cannot be removed by holding just a few securities. Asset allocation is a primary management tool."),
  c("real", "A client's real return is nominal return adjusted for what?", ["Inflation", "Tax lot selection", "CUSIP assignment", "State filing fees"], 0, "Real return measures the actual growth in purchasing power. It is especially important for long-term goals.")
];
const s66Vehicles = [
  c("stock", "Common stock is generally more appropriate for which objective than Treasury bills?", ["Long-term capital appreciation", "Near-certain principal stability", "Known maturity value", "Guaranteed income"], 0, "Stocks are generally used for growth while Treasury bills are used for short-term stability. The tradeoff is higher volatility and market risk."),
  c("bond", "What risk is especially relevant to lower-rated corporate bonds?", ["Default risk", "Breakpoint risk", "Proxy risk", "Rights-offering risk"], 0, "Lower-rated bonds carry more credit risk than investment-grade issues. The higher yield is compensation for that risk."),
  c("open-end", "An open-end mutual fund investor buys and redeems shares at what basis?", ["Next computed NAV", "A negotiated exchange price", "Par value", "A fixed redemption value"], 0, "Open-end funds transact at NAV after orders are accepted. They do not trade intraday like exchange-listed stocks."),
  c("closed-end", "Why can a closed-end fund trade at a premium or discount to NAV?", ["Supply and demand in the market", "A legal requirement to redeem at par", "FDIC insurance", "State administrator pricing"], 0, "Closed-end funds trade in the market, so their shares can move above or below portfolio value. That is a structural feature of the product."),
  c("annuity", "A variable annuity differs from a fixed annuity because its value generally does what?", ["Fluctuates with underlying investment performance", "Remains fixed by contract", "Tracks the federal funds rate exactly", "Avoids all surrender charges"], 0, "Variable annuities place investment risk on the owner through subaccounts. Fixed annuities rely more on insurer guarantees.")
];
const s66Recs = [
  c("moderate", "For a moderate-risk client, what is generally more suitable than concentrating the portfolio in one speculative sector?", ["A diversified allocation matched to objectives", "A single leveraged position", "All uncovered options", "One illiquid private placement"], 0, "Diversified allocations are generally more consistent with prudent recommendation practice than concentrated speculation. The strategy should fit the client's actual profile."),
  c("risk-profile", "If a client with low stated risk tolerance asks about a highly volatile product, what should the adviser do first?", ["Compare the product's risk with the client's full profile before recommending it", "Proceed because the client asked", "Ignore the risk tolerance", "Guarantee losses will be temporary"], 0, "Client interest in a product does not remove suitability obligations. Advisers should reconcile the product's characteristics with the client's profile."),
  c("time-horizon", "A goal occurring in less than two years generally supports what type of allocation more than a 20-year retirement goal?", ["A more conservative and liquid allocation", "A more leveraged allocation", "Exclusive small-cap exposure", "Unlimited-downside speculation"], 0, "Shorter horizons reduce the client's ability to recover from volatility. Liquidity and principal stability become more important as the goal nears."),
  c("tax", "Why should an adviser consider a client's marginal tax bracket when comparing investments?", ["To compare after-tax suitability", "To decide whether the client may open an account", "To determine the issuer's credit rating", "To remove disclosure obligations"], 0, "Taxes can materially change realized client outcomes. After-tax evaluation often changes which product is truly more suitable."),
  c("rebalancing", "Portfolio rebalancing is generally used to do what?", ["Return asset weights toward the intended allocation", "Guarantee outperformance every year", "Avoid all taxes", "Replace financial planning"], 0, "Rebalancing is a discipline that brings the portfolio back toward its target risk profile. It does not guarantee returns."),
  c("emergency", "Why is an illiquid private fund usually unsuitable for a client's emergency reserve?", ["Emergency funds need stability and ready access", "Private funds are federally insured", "Emergency funds must be in equities", "Private funds settle faster than cash"], 0, "Emergency reserves are for near-term needs, so liquidity and stability matter most. Illiquid investments undermine that purpose.")
];
const s66Laws = [
  c("bd-register", "Under the Uniform Securities Act, why is broker-dealer registration status important in a state?", ["State-law obligations depend on where and with whom the firm does business", "It determines Treasury yields", "It removes antifraud rules", "It sets fund breakpoints"], 0, "State registration rules differ depending on place of business and activity with residents. Understanding that framework is central to Series 66 state-law analysis."),
  c("agent", "An agent generally registers at the state level in connection with acting on behalf of whom?", ["A broker-dealer or issuer", "A federal court", "A transfer agent only", "An auditor"], 0, "Agents are individuals who represent broker-dealers or issuers in effecting or attempting to effect securities transactions. Their registration obligations are distinct from the firm's."),
  c("iar", "An investment adviser representative is generally the person who does what?", ["Represents an adviser in giving advice or managing accounts", "Acts only as a passive shareholder", "Clears customer trades", "Files municipal tax returns"], 0, "State law often regulates adviser representatives separately from advisory firms. The representative role centers on advice and account management."),
  c("exempt-security", "Why does an exempt security matter under state law?", ["It may be exempt from registration even though antifraud rules still apply", "It is exempt from all laws", "It guarantees principal", "It removes the need for agent registration"], 0, "An exemption from registration does not mean an exemption from honesty. Antifraud provisions still apply to exempt securities."),
  c("exempt-transaction", "A transaction exemption generally affects what?", ["Whether a particular transaction must be registered", "Whether fraud is permitted", "Whether records may be destroyed", "Whether clients can sue"], 0, "Exempt transactions can remove registration burdens for specific scenarios. They do not eliminate antifraud duties."),
  c("administrator", "A state administrator's authority commonly includes what?", ["Investigating and enforcing state securities laws", "Guaranteeing investment returns", "Approving each portfolio allocation", "Setting market prices"], 0, "State administrators have investigation and enforcement powers. They use those powers to protect investors and police violations."),
  c("cease", "What is the purpose of a cease-and-desist order?", ["To stop ongoing or threatened violations", "To approve an IPO", "To liquidate a customer's account", "To price a municipal bond"], 0, "Cease-and-desist orders are enforcement tools. They are designed to halt harmful conduct quickly."),
  c("notice-filing", "A notice filing is most commonly associated with what?", ["A federally covered adviser or security entering a state framework", "A margin account application", "A trade confirmation", "A closed-end fund premium"], 0, "Federal preemption can still leave room for state notice filings and fees. That distinction is tested frequently in state-law questions."),
  c("dishonest", "Guaranteeing that an investment will never lose value would most likely be considered what?", ["A dishonest or unethical practice", "A permitted statement if disclosed later", "An exempt communication", "A custody rule"], 0, "Promises of no loss are misleading in most securities contexts. State unethical-practice rules target that kind of misrepresentation."),
  c("commingling", "How is commingling client funds with firm funds generally viewed?", ["As prohibited or highly improper", "As efficient bookkeeping", "As irrelevant if performance is good", "As a substitute for custody controls"], 0, "Keeping client assets separate is a core investor-protection principle. Commingling can facilitate misuse and create major compliance risk.")
];

function series7Options(): Question[] {
  const out: Question[] = [];
  let n = 1;
  for (const strike of [45, 50, 55, 60, 65]) for (const p of [2, 3, 4, 5]) out.push(q("Series 7", L.s7[2], `s7-opt-lc-${n++}`, `A customer buys 1 XYZ ${strike} call for a premium of ${p}. At what stock price at expiration does the position break even, ignoring commissions?`, [`$${strike + p}`, `$${strike - p}`, `$${strike}`, `$${p}`], 0, `A long call breaks even at the strike price plus the premium paid. Above that price, intrinsic value begins to offset the option cost.`));
  for (const strike of [45, 50, 55, 60, 65]) for (const p of [2, 3, 4, 5]) out.push(q("Series 7", L.s7[2], `s7-opt-lp-${n++}`, `A customer buys 1 XYZ ${strike} put for a premium of ${p}. At what stock price at expiration does the position break even, ignoring commissions?`, [`$${strike - p}`, `$${strike + p}`, `$${strike}`, `$${p}`], 0, `A long put breaks even at the strike price minus the premium paid. Below that price, the position's intrinsic value exceeds the premium cost.`));
  for (const basis of [42, 48, 52, 58, 63]) for (const strike of [45, 50, 55, 60]) out.push(q("Series 7", L.s7[2], `s7-opt-cc-${n++}`, `A customer owns XYZ at a cost basis of ${basis} and writes 1 XYZ ${strike} call for a premium of 3. If the stock is called away, what is the maximum gain per share?`, [`$${strike - basis + 3}`, `$${strike + 3}`, `$3`, `Unlimited`], 0, `For a covered call, maximum gain equals the strike price minus stock cost basis plus the premium received. Once the stock is called away, upside above the strike is capped.`));
  for (const basis of [42, 48, 52, 58, 63]) for (const strike of [40, 45, 50, 55]) out.push(q("Series 7", L.s7[2], `s7-opt-pp-${n++}`, `A customer buys stock at ${basis} and purchases a protective ${strike} put for a premium of 2. What is the maximum loss per share before commissions?`, [`$${basis + 2 - strike}`, `$${basis - strike}`, `$2`, `$${strike + 2}`], 0, `A protective put sets a floor on the stock position. Maximum loss equals stock cost basis plus the put premium minus the put strike price.`));
  for (const strike of [45, 50, 55, 60]) for (const cp of [2, 3, 4]) for (const pp of [2, 3]) out.push(q("Series 7", L.s7[2], `s7-opt-straddle-${n++}`, `A customer buys a long straddle with a ${strike} call costing ${cp} and a ${strike} put costing ${pp}. What is the upside break-even price at expiration?`, [`$${strike + cp + pp}`, `$${strike - cp - pp}`, `$${cp + pp}`, `$${strike + cp}`], 0, `A long straddle has two break-even points. The upside break-even equals the common strike price plus total premiums paid.`));
  for (const low of [45, 50, 55, 60]) for (const high of [50, 55, 60, 65]) if (high > low) out.push(q("Series 7", L.s7[2], `s7-opt-bcs-${n++}`, `A customer establishes a bull call spread by buying the ${low} call and selling the ${high} call for a net premium of 2. What is the maximum gain per share?`, [`$${high - low - 2}`, `$${high - low + 2}`, `$2`, `Unlimited`], 0, `A debit bull call spread has limited risk and limited reward. Maximum gain equals the difference between strike prices minus the net premium paid.`));
  for (const high of [55, 60, 65, 70]) for (const low of [45, 50, 55, 60]) if (high > low) out.push(q("Series 7", L.s7[2], `s7-opt-bps-${n++}`, `A customer establishes a bear put spread by buying the ${high} put and selling the ${low} put for a net premium of 3. What is the break-even price at expiration?`, [`$${high - 3}`, `$${low + 3}`, `$3`, `$${high + 3}`], 0, `A bear put spread profits from a decline in the underlying. Break-even equals the long put strike price minus the net premium paid.`));
  return out;
}
const s7F3Products = [
  c("muni-tax", "For a high-bracket investor, municipal bond income may be attractive mainly because of what feature?", ["Interest is often exempt from federal income tax", "It is insured against market loss", "It always has lower duration than Treasuries", "It guarantees higher yields than corporates"], 0, "Municipal bonds often appeal to high-bracket investors because interest is commonly exempt from federal income tax. Tax-equivalent yield helps compare them with taxable bonds."),
  c("duration", "Which bond is generally more sensitive to interest-rate changes, all else equal?", ["The bond with the longer duration", "The bond with the shorter duration", "The bond with the lower par value", "The bond with the lower coupon only"], 0, "Duration is a common measure of price sensitivity to interest-rate changes. Higher duration generally means larger price movement for a given yield shift."),
  c("annuity", "Before recommending a variable annuity, which factor is especially important?", ["The customer's need for tax deferral and tolerance for fees and market risk", "Whether the customer wants FDIC insurance", "Whether the customer wants same-day settlement", "Whether the customer wants short-term trading"], 0, "Variable annuities can be complex and costly. They are generally suitable only when tax deferral and insurance features align with the customer's needs."),
  c("margin", "What is the main suitability concern with recommending purchases on margin?", ["Leverage can magnify losses and create interest expense", "Margin eliminates volatility", "Margin creates tax-free income", "Margin removes diversification needs"], 0, "Margin amplifies gains and losses and can trigger calls or interest costs. It is often unsuitable for low-risk or liquidity-sensitive clients."),
  c("reit", "A listed equity REIT is often recommended primarily for what objective?", ["Income and real estate exposure", "Short-term principal protection", "Guaranteed tax-free interest", "Currency hedging only"], 0, "Equity REITs can provide income and diversified exposure to real estate. They still carry market and sector risk."),
  c("bond-ladder", "Why might a bond ladder be recommended to a client needing periodic reinvestment opportunities?", ["It staggers maturities and reduces reinvestment timing risk", "It guarantees the highest yield", "It removes all credit risk", "It is allowed only for institutions"], 0, "A bond ladder spreads maturities over time. That can help manage cash flows and reduce the impact of changing rates on the full portfolio.")
];
const authored = {
  sie: [
    ...expand("SIE", L.sie[0], "sie-capital", sieCapital, 48),
    ...expand("SIE", L.sie[1], "sie-products", sieProducts, 132),
    ...expand("SIE", L.sie[2], "sie-trading", sieTrading, 93),
    ...expand("SIE", L.sie[3], "sie-reg", sieReg, 27)
  ],
  series7: [
    ...expand("Series 7", L.s7[0], "s7-f1", s7F1, 36),
    ...expand("Series 7", L.s7[1], "s7-f2", s7F2, 44),
    ...series7Options(),
    ...expand("Series 7", L.s7[2], "s7-f3", s7F3Products, 364 - series7Options().length),
    ...expand("Series 7", L.s7[3], "s7-f4", s7F4, 56)
  ],
  series65: [
    ...expand("Series 65", L.s65[0], "s65-econ", s65Econ, 60),
    ...expand("Series 65", L.s65[1], "s65-vehicles", s65Vehicles, 100),
    ...expand("Series 65", L.s65[2], "s65-recs", s65Recs, 120),
    ...expand("Series 65", L.s65[3], "s65-laws", s65Laws, 120)
  ],
  series66: [
    ...expand("Series 66", L.s66[0], "s66-econ", s66Econ, 20),
    ...expand("Series 66", L.s66[1], "s66-vehicles", s66Vehicles, 80),
    ...expand("Series 66", L.s66[2], "s66-recs", s66Recs, 120),
    ...expand("Series 66", L.s66[3], "s66-laws", s66Laws, 180)
  ]
};

fs.mkdirSync(outDir, { recursive: true });
writeExamFile("sie", "SIE_AUTHORED_QUESTIONS", authored.sie);
writeExamFile("series7", "SERIES7_AUTHORED_QUESTIONS", authored.series7);
writeExamFile("series65", "SERIES65_AUTHORED_QUESTIONS", authored.series65);
writeExamFile("series66", "SERIES66_AUTHORED_QUESTIONS", authored.series66);
console.log(JSON.stringify({ sie: authored.sie.length, series7: authored.series7.length, series65: authored.series65.length, series66: authored.series66.length }, null, 2));


